def Character;
def AreaObj;
def SPEED = 10;
def Velocity = 0;
def musicplayerobj;
def audioplayerobj;

def jumpStr = 4;
def speedX = 0;
def speedY = 0;
def gravity = 0.3;
def friction = 0.95;
def runStr = 0.1;

def left = 0;
def right = 0;
def up = 0;
def onGround = 0;
def ground = 525;

def AnimPlayer;
def Cam;
def Circle;
def Poly;

def init(delta) =
 Character = Engine_get_object("Game_Character");
 AreaObj = Engine_get_object("Wall");
 Character = Character.sub_groups.0;
 AnimPlayer = Engine_AnimationPlayerObject();
 Circle = Engine_CircleObject();
 Poly = Engine_PolygonObject();

 Circle.set_radius(50);
 Circle.set_segments(30);
 Circle.pos_x = 300;
 Circle.pos_y = 300;

 Poly.pos_x = 200;
 Poly.pos_y = 200;
 Poly.push_polygon(0, 0);
 Poly.push_polygon(10, 0);
 Poly.push_polygon(10, 10);
 Poly.push_polygon(0, 10);

 AnimPlayer.push_frame(Engine_AnimationFrameObject(
    0,
    1000,
    Engine_get_object("Game_Character_Sprite"),
    false,
    "visible"
 ));
 AnimPlayer.push_frame(Engine_AnimationFrameObject(
     1000,
     2000,
     Engine_get_object("Game_Character_Sprite"),
     true,
     "visible"
  ));
 AnimPlayer.push_frame(Engine_AnimationFrameObject(
    2000,
    3000,
    Engine_get_object("Game_Character_Sprite"),
    "example/icon.png",
    "sprite_resource"
 ));
 Engine_link_camera(Character.sub_groups.0.sub_groups.0);
 AnimPlayer.set_replay_status(true);
 Engine_render_objects_push(AnimPlayer);
 Engine_render_objects_push(Circle);
 Engine_render_objects_push(Poly);

 musicplayerobj = Engine_MusicPlayerObject("example/digits.wav");
 audioplayerobj = Engine_AudioPlayerObject("example/digits.wav");
 IO_println(musicplayerobj);
;

EngineWindow_set_window_opacity(0.5);
EngineWindow_set_vsync(true);

def is_music_plays = false;
def is_audio_plays = false;

def update(delta) =
 if(EngineIO_is_key_just_pressed(EngineIO_Key_P)) =
  is_music_plays = !is_music_plays;
  if(is_music_plays) =
    musicplayerobj.play_music();
  ; else =
    musicplayerobj.stop_music();
  ;
 ;


 if(EngineIO_is_key_just_pressed(EngineIO_Key_O)) =
   is_audio_plays = !is_audio_plays;
   if(is_audio_plays) =
     audioplayerobj.play_audio();
   ; else =
     audioplayerobj.stop_audio();
   ;
  ;

 if(EngineIO_is_key_just_pressed(EngineIO_Key_F)) =
  if(EngineWindow_get_window_mode() == EngineWindow_Fullscreen) =
   EngineWindow_set_window_mode(EngineWindow_Windowed);
  ; else =
   EngineWindow_set_window_mode(EngineWindow_Fullscreen);
  ;
 ;

 if(EngineIO_is_key_pressed(EngineIO_Key_S)) =
  IO_println("s press");
  Character.sub_groups.0.pos_y = Character.sub_groups.0.pos_y + 50;
  # Character.sub_groups.0.move(0, -10);
 ;
 if(EngineIO_is_key_pressed(EngineIO_Key_A)) =
   IO_println("a press");
   Character.sub_groups.0.pos_x = Character.sub_groups.0.pos_x - 50;
   # Character.sub_groups.0.move(10, 0);
   left = 1;
  ;
  if(EngineIO_is_key_pressed(EngineIO_Key_D)) =
   IO_println("d press");
   Character.sub_groups.0.pos_x = Character.sub_groups.0.pos_x + 50;
   # Character.sub_groups.0.move(-10, 0);
   right = 1;
  ;
  if(EngineIO_is_key_pressed(EngineIO_Key_W)) =
   IO_println("w press");
   Character.sub_groups.0.pos_y = Character.sub_groups.0.pos_y - 50;
   # Character.sub_groups.0.move(0, 10);
   up = 1;
  ;
  if(EngineIO_is_key_released(EngineIO_Key_A)) =
   IO_println("a release");
   left = 0;
  ;
  if(EngineIO_is_key_released(EngineIO_Key_G)) =
   IO_println("Animation start");
   AnimPlayer.run_animation();
  ;
  if(EngineIO_is_key_released(EngineIO_Key_D)) =
   IO_println("d release");
   right = 0;
  ;
  if(EngineIO_is_key_released(EngineIO_Key_W)) =
   IO_println("w release");
   up = 0;
  ;
;

# speedX = speedX + (right * runStr) - (left * runStr);
#   Character.pos_x = Character.pos_x + speedX * friction;
#   speedY = speedY - (onGround * up * jumpStr) - gravity;
#   Character.pos_y = Character.pos_y - speedY;
#   if((Character.pos_y + Character.height) >= ground) =
#    speedY = 0;
#    Character.pos_y = ground - Character.height;
#    onGround = 1;
#   ; else =
#    onGround = 0;
#   ;