// MIT License
//
// Copyright (c) 2024 Ferhat Geçdoğan All Rights Reserved.
// Distributed under the terms of the MIT License.
//
#pragma once
#include "module_helpers.hpp"
#include <fescript/fescript_class.hpp>
#include <fescript/fescript_callable.hpp>
#include <types/predefined.hpp>
#include <unordered_map>
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>

#define ENGINEIO_GLOBAL_CONSTANT(name, value) this->globals->define(name, static_cast<idk::f80>(value));
#define ENGINEIO_MODULE(name, arg_count) DEFINE_MODULE_CLASS(name, EngineIO, arg_count)

#define ENGINEIO_INIT_CONSTANTS() \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_A", GLFW_KEY_A) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_B", GLFW_KEY_B) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_C", GLFW_KEY_C) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_D", GLFW_KEY_D) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_E", GLFW_KEY_E) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F", GLFW_KEY_F) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_G", GLFW_KEY_G) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_H", GLFW_KEY_H) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_I", GLFW_KEY_I) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_J", GLFW_KEY_J) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_K", GLFW_KEY_K) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_L", GLFW_KEY_L) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_M", GLFW_KEY_M) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_N", GLFW_KEY_N) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_O", GLFW_KEY_O) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_P", GLFW_KEY_P) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Q", GLFW_KEY_Q) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_R", GLFW_KEY_R) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_S", GLFW_KEY_S) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_T", GLFW_KEY_T) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_U", GLFW_KEY_U) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_V", GLFW_KEY_V) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_W", GLFW_KEY_W) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_X", GLFW_KEY_X) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Y", GLFW_KEY_Y) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Z", GLFW_KEY_Z) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_1", GLFW_KEY_1) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_2", GLFW_KEY_2) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_3", GLFW_KEY_3) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_4", GLFW_KEY_4) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_5", GLFW_KEY_5) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_6", GLFW_KEY_6) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_7", GLFW_KEY_7) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_8", GLFW_KEY_8) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_9", GLFW_KEY_9) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_0", GLFW_KEY_0) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Escape", GLFW_KEY_ESCAPE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Backspace", GLFW_KEY_BACKSPACE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Tab", GLFW_KEY_TAB) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Space", GLFW_KEY_SPACE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Minus", GLFW_KEY_MINUS) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Equals", GLFW_KEY_EQUAL) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_LeftBracket", GLFW_KEY_LEFT_BRACKET) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_RightBracket", GLFW_KEY_RIGHT_BRACKET) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Backslash", GLFW_KEY_BACKSLASH) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Semicolon", GLFW_KEY_SEMICOLON) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Apostrophe", GLFW_KEY_APOSTROPHE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Grave", GLFW_KEY_GRAVE_ACCENT) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Comma", GLFW_KEY_COMMA) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Period", GLFW_KEY_PERIOD) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Slash", GLFW_KEY_SLASH) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_CapsLock", GLFW_KEY_CAPS_LOCK) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F1", GLFW_KEY_F1) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F2", GLFW_KEY_F2) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F3", GLFW_KEY_F3) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F4", GLFW_KEY_F4) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F5", GLFW_KEY_F5) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F6", GLFW_KEY_F6) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F7", GLFW_KEY_F7) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F8", GLFW_KEY_F8) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F9", GLFW_KEY_F9) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F10", GLFW_KEY_F10) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F11", GLFW_KEY_F11) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F12", GLFW_KEY_F12) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PrintScreen", GLFW_KEY_PRINT_SCREEN) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_ScrollLock", GLFW_KEY_SCROLL_LOCK) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pause", GLFW_KEY_PAUSE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Insert", GLFW_KEY_INSERT) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Home", GLFW_KEY_HOME) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PageUp", GLFW_KEY_PAGE_UP) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Delete", GLFW_KEY_DELETE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_End", GLFW_KEY_END) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PageDown", GLFW_KEY_PAGE_DOWN) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Right", GLFW_KEY_RIGHT) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Left", GLFW_KEY_LEFT) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Down", GLFW_KEY_DOWN) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Up", GLFW_KEY_UP) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PadDivide", GLFW_KEY_KP_DIVIDE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PadMultiply", GLFW_KEY_KP_MULTIPLY) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PadMinus", GLFW_KEY_KP_ADD) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PadPlus", GLFW_KEY_KP_SUBTRACT) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_PadEnter", GLFW_KEY_KP_ENTER) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad1", GLFW_KEY_KP_1) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad2", GLFW_KEY_KP_2) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad3", GLFW_KEY_KP_3) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad4", GLFW_KEY_KP_4) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad5", GLFW_KEY_KP_5) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad6", GLFW_KEY_KP_6) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad7", GLFW_KEY_KP_7) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad8", GLFW_KEY_KP_8) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Pad9", GLFW_KEY_KP_9) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F13", GLFW_KEY_F13) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F14", GLFW_KEY_F14) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F15", GLFW_KEY_F15) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F16", GLFW_KEY_F16) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F17", GLFW_KEY_F17) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F18", GLFW_KEY_F18) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F19", GLFW_KEY_F19) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F20", GLFW_KEY_F20) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F21", GLFW_KEY_F21) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F22", GLFW_KEY_F22) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F23", GLFW_KEY_F23) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_F24", GLFW_KEY_F24) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Key_Menu", GLFW_KEY_MENU) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Button_Left", GLFW_MOUSE_BUTTON_LEFT) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Button_Middle", GLFW_MOUSE_BUTTON_MIDDLE) \
  ENGINEIO_GLOBAL_CONSTANT("EngineIO_Button_Right", GLFW_MOUSE_BUTTON_RIGHT)

namespace fescript {
ENGINEIO_MODULE(IsKeyPressed, 1)
ENGINEIO_MODULE(IsKeyJustPressed, 1)
ENGINEIO_MODULE(IsKeyReleased, 1)
ENGINEIO_MODULE(IsMouseButtonPressed, 1)
ENGINEIO_MODULE(IsMouseButtonJustPressed, 1)
ENGINEIO_MODULE(IsMouseButtonReleased, 1)
} // namespace fescript

#undef ENGINEIO_MODULE